#!/usr/bin/env bash
# This script displays the content of the current directory with the part of the name after the first dash

for file in */
do
  # Remove the trailing slash and cut the part after the first dash
  echo "$file" | sed 's/^[^-]*-//'
done

